name: Eclipse 2020-03 (4.15) on Java 11
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CLOUDSDK_CORE_DISABLE_USAGE_REPORTING: true
      ECLIPSE_TARGET: 2020-03

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8  # Java 8 required for compilation.
      - name: Set JDK 8 toolchain
        run: |
          sed -i.bak -e "s,JDK_8_HOME,${JAVA_HOME}," .github/workflows/toolchains.xml

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set JDK 11 toolchain
        run: |
          sed -i.bak -e "s,JDK_11_HOME,${JAVA_HOME}," .github/workflows/toolchains.xml

      - uses: google-github-actions/setup-gcloud@v0.2.0

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.ECLIPSE_TARGET }}

      - name: Run tests
        env:
          MAVEN_OPTS: '-Xmx700m -Dorg.slf4j.simpleLogger.showDateTime=true'
        run: |
          # google-github-actions/setup-gcloud@v0.2.0 sets up gcloud at, e.g,.
          # "/opt/hostedtoolcache/gcloud/325.0.0/x64". appengine-plugins-core
          # fails to find it, since the directory doesn't end with
          # "google-cloud-sdk". Instead, appengine-plugins-core picks up the SDK
          # at "/usr/lib/google-cloud-sdk" managed by a package manager. As a
          # workaround, create a symlink at $HOME and add it to $PATH.
          ln -s "$( dirname "$( dirname "$( which gcloud )")")" \
            "${HOME}"/google-cloud-sdk
          ls -ld "${HOME}"/google-cloud-sdk
          export PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
          gcloud components install app-engine-java --quiet

          xvfb-run mvn --show-version --batch-mode --fail-at-end \
            --toolchains=.github/workflows/toolchains.xml \
            -Derrorprone -Dci-build -Declipse-target=${{ env.ECLIPSE_TARGET }} \
            clean verify
